const COCKTAIL_LIST = "COCKTAIL_LIST";
const FAVORITE_LIST = "FAVORITE_LIST";
const ADD_TO_FAVORITE_ITEM = "ADD_TO_FAVORITE_ITEM";
const REMOVE_FROM_FAVORITE_ITEM = "REMOVE_FROM_FAVORITE_ITEM";

export {
  COCKTAIL_LIST,
  FAVORITE_LIST,
  ADD_TO_FAVORITE_ITEM,
  REMOVE_FROM_FAVORITE_ITEM,
};
